name       : usysconf
version    : 0.5.1
release    : 22
source     :
    - git|https://github.com/solus-project/usysconf.git : 2794a8f0a2ba270dee4cc5dfad7c2ba15eb1ce4f
license    : GPL-2.0
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.

    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.

    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=false \
                     -Dwith-vbox-restart=true
build      : |
    %meson_build
install    : |
    %meson_install
