name       : usysconf
version    : 0.5.5
release    : 34
source     :
    - https://github.com/getsolus/usysconf/releases/download/v0.5.5/usysconf-v0.5.5.tar.xz : a3ad6057542eedcedda7287132a54596822abf523da4eb8f8266f9a2db3eb2a2
license    : GPL-2.0-only
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.

    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.

    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=true \
                     -Dwith-vbox-restart=true
build      : |
    %ninja_build
install    : |
    %ninja_install
