name       : usysconf
version    : 0.5.4
release    : 29
source     :
    - https://github.com/getsolus/usysconf/releases/download/v0.5.4/usysconf-v0.5.4.tar.xz : c0a4bc82adec3b38c09b677b93c5f76b6e4b7cf2d0e587b1ead7c8a78fcd81de
license    : GPL-2.0-only
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.

    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.

    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=true \
                     -Dwith-vbox-restart=true
build      : |
    %ninja_build
install    : |
    %ninja_install
