name       : usysconf
version    : 0.5.1
release    : 21
source     :
    - https://github.com/solus-project/usysconf/releases/download/v0.5.1/usysconf-0.5.1.tar.xz : 6d3838c7c0d997b7e115c96b1752790cb4d63a3a185e8ec1a46e05027436fc29
license    : GPL-2.0
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.

    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.

    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    %apply_patches
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=false \
                     -Dwith-vbox-restart=true
build      : |
    %meson_build
install    : |
    %meson_install
