name       : usysconf
version    : 0.0.1
release    : 2
source     :
    - https://github.com/solus-project/usysconf/releases/download/v0.0.1/usysconf-0.0.1.tar.xz : 0a770c0d7159898b6fa1b971cbe068ab2e93d403719c526786b1ed41b2696a67
license    : GPL-2.0
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.
    
    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.
    
    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    %apply_patches
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=false
build      : |
    %meson_build
install    : |
    %meson_install
