name       : usysconf
version    : 0.1.0
release    : 9
source     :
    - https://github.com/solus-project/usysconf/releases/download/v0.1.0/usysconf-0.1.0.tar.xz : c8a6a28dc8470d580ccd48414cc13781fd1423770117d50f46a2756a6bb81314
license    : GPL-2.0
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.

    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.

    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    %apply_patches
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=false
build      : |
    %meson_build
install    : |
    %meson_install
