name       : usysconf
version    : 0.5.2
release    : 23
source     :
    - https://github.com/solus-project/usysconf/releases/download/v0.5.2/usysconf-0.5.2.tar.xz : 49e6ea6a0ebe593d6f937dbd1d6638707c0657b72d964c0b5b54704ab088bc32
license    : GPL-2.0
component  : system.base
summary    : System configuration component
description: |
    usysconf is the configuration component of the Solus update architecture.
    It is responsible for maintaining system consistency and health over time,
    and can be directly interacted with via the CLI interface.

    usysconf is used by the package manager to finish up configuration of all
    aspects of the system in an incremental fashion.

    usysconf is a Solus project.
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    export CC=musl-gcc
    %meson_configure -Dwith-static-binary=true \
                     -Dwith-systemd-reexec=false \
                     -Dwith-vbox-restart=true
build      : |
    %meson_build
install    : |
    %meson_install
